version: 2
updates:
  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/app-front-nuxt3" # Location of package manifests
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
